### What is Pandas
Padas is a fast, powerful, flexible and easy to open source data analysis and manipulation tool, build on a top of the python programming language

Pandas Series<br>
A pandas Series is like a column in a table, it is a 1-D array holding data of any type.

### importing Pandas

In [1]:
import pandas as pd
import numpy as np

### Series from list

In [2]:
# string
country=['india','pakistan','USA','Srilanka','Bangladesh']
pd.Series(country)

0         india
1      pakistan
2           USA
3      Srilanka
4    Bangladesh
dtype: object

In [3]:
#integer Series
run=[14,45,100,92,108]
run=pd.Series(run)
print(run)

0     14
1     45
2    100
3     92
4    108
dtype: int64


In [4]:
# custom index
marks=[25,30,45,50,49]
Subjects=['Maths','Physics','Chemistry','English','Hindi']
pd.Series(marks, index=Subjects)

Maths        25
Physics      30
Chemistry    45
English      50
Hindi        49
dtype: int64

In [5]:
# Setting a name
pd.Series(marks, index=Subjects , name='Neelesh ke Marks')


Maths        25
Physics      30
Chemistry    45
English      50
Hindi        49
Name: Neelesh ke Marks, dtype: int64

### Series from dist

In [6]:
marks={
    'Maths':25,
    'Physics':30,
    'Chemistry':45,
    'English':50,
    'Hindi':49
}
marks_series=pd.Series(marks, name='Neelesh ke Marks')
print(marks_series)

Maths        25
Physics      30
Chemistry    45
English      50
Hindi        49
Name: Neelesh ke Marks, dtype: int64


### Series atributes

In [7]:
# Size
marks_series.size

5

In [8]:
#dtype
marks_series.dtype

dtype('int64')

In [9]:
#name
marks_series.name

'Neelesh ke Marks'

In [10]:
#is_unique
marks_series.is_unique

pd.Series([1,1,2,3,4,5]).is_unique

False

In [11]:
#index
marks_series.index

Index(['Maths', 'Physics', 'Chemistry', 'English', 'Hindi'], dtype='object')

In [12]:
print(type(run.index))
run.index

<class 'pandas.core.indexes.range.RangeIndex'>


RangeIndex(start=0, stop=5, step=1)

In [13]:
# value
print(type(marks_series.values))
marks_series.values

<class 'numpy.ndarray'>


array([25, 30, 45, 50, 49])

### Series using read_csv

In [14]:
# Read one column of a csv file
subs = pd.read_csv('Datasets/subs.csv').squeeze("columns")
print(subs)


0       48
1       57
2       40
3       43
4       44
      ... 
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64


In [15]:
# with 2 columns
runs=pd.read_csv('Datasets/Kohli_ipl.csv',index_col='match_no').squeeze("columns")
runs

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [16]:
Movies = pd.read_csv('Datasets/bollywood.csv',index_col='movie').squeeze("columns")
Movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...       
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

### Series methods

- Head() and tails()

In [17]:
# head and tail
subs.head()

0    48
1    57
2    40
3    43
4    44
Name: Subscribers gained, dtype: int64

In [18]:
runs.tail()

match_no
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

- Sample()

In [19]:
# sample function
Movies.sample(3)

movie
Aisa Kyon Hota Hai?     Rati Agnihotri
Bioscopewala           Danny Denzongpa
Hawas (2004 film)           Shawar Ali
Name: lead, dtype: object

- Value_count()

In [20]:
# value counts
Movies.value_counts()

lead
Akshay Kumar            48
Amitabh Bachchan        45
Ajay Devgn              38
Salman Khan             31
Sanjay Dutt             26
                        ..
Tanishaa Mukerji         1
Tanuja                   1
Ankit                    1
Rakhee Gulzar            1
Geetika Vidya Ohlyan     1
Name: count, Length: 566, dtype: int64

- sort value()

In [21]:
# sort values ->inplace sorting
runs.sort_values()

match_no
8        0
87       0
93       0
91       0
206      0
      ... 
164    100
120    100
123    108
126    109
128    113
Name: runs, Length: 215, dtype: int64

In [22]:
# sort runs in descending order
runs.sort_values(ascending=False).head(2).values[0:2]

array([113, 109])

In [23]:
# use value
runs.head(10).values[0:5]

array([ 1, 23, 13, 12,  1])

In [24]:
# inplace sorting
runs.sort_values(inplace=True)
runs

ValueError: This Series is a view of some other array, to sort in-place you must create a copy

In [ ]:
#sort index -> inplace -> movies
Movies.sort_index()
Movies

In [ ]:
Movies.sort_values(ascending=True)

### Series Math Methods

- Count()

In [ ]:
# count()
runs.count()

- Sum -> product

In [ ]:
# sum()
subs.sum()

In [ ]:
# prod()
subs.prod()

- Mean -> median -> mode -> std -> var

In [ ]:
# mean()
subs.mean()

In [ ]:
# Median
runs.median()

In [ ]:
# Mode()
Movies.mode()     

In [ ]:
# standard deviation
runs.std()

In [ ]:
# varience
runs.var()

- Min / Max

In [ ]:
# Minimum
subs.min()

In [ ]:
# maximum
subs.max()

- Describe

In [ ]:
# Discribe
subs.describe()

### Series indexing

In [ ]:
x=pd.Series([1,2,3,4,5])
x[1:4]


In [ ]:
 # Nagative indexing never work in pandas
x[-1]

In [ ]:
Movies

In [ ]:
# -ve indexing work in strings in pandas 
Movies[-1]

In [ ]:
# two ways to access data in pandas
print(Movies[0])
print(Movies['Uri: The Surgical Strike'])

### Series Slicing

In [ ]:
# series slicing
runs[1:4]

In [ ]:
Movies[-5:]

In [ ]:
# fancy indexing
runs[[10,3,11]]

### Editing Series

In [ ]:
marks_series

In [ ]:
marks_series[1]=40
marks_series

In [ ]:
# adding new value in series
marks_series['Sanskrit']=20
marks_series

In [ ]:
# slicing
run[2:4]=[100,200]
run

In [ ]:
# fancy indexing
run[[0,3,4]] = [100,300,400]
run

In [ ]:
# using index lable
Movies['Awara Paagal Deewana']='Sahrukh Khan'
Movies


### Series with Python functions

- len
- type
- dir
- sorted
- Min
- max

In [ ]:
print(len(Movies))
print(type(Movies))
print(dir(subs))
print(sorted(runs))
print(min(runs))
print(max(runs))

- Type Conversion

In [ ]:
marks_series

In [ ]:
dict(marks_series)

- Membership Operator

In [ ]:
'Battalion 609' in Movies

In [ ]:
# Loop
# for i in Movies:
#     print(i)

- Arithmetic Operaorts

In [ ]:
# This is a one more example of broadcasting
10+marks_series

- Relational Operator

In [ ]:
runs>=90

### Boolean Indexing on Series

In [ ]:
# finding how many times runs are greater than or equal to 90
runs[runs>=90].size

In [ ]:
# how many ducks in runs
runs[runs==0].size

In [ ]:
# Count number of a day when I had more than 200 subs a day
subs[subs>200].count()

In [ ]:
num_movies=Movies.value_counts()
num_movies[num_movies>25]

### Some Important Series Methods

In [ ]:
# astype
# between
# clip
# drop_duplicates
# isnull
# dropna
# fillna
# isin
# apply

In [ ]:
#astype
import sys
sys.getsizeof(runs)

In [ ]:
sys.getsizeof(runs.astype('int16'))

In [ ]:
runs[runs.between(50,100)].size

In [ ]:
subs.clip(100,200)

In [ ]:
a=pd.Series([1,1,1,2,2,6,4,5,6,7,8,9])
a.duplications()

In [ ]:
#drop_duplicates
a.drop_duplicates()

In [ ]:
a.drop_duplicates(keep='last')

In [ ]:
numvalues=pd.Series([1,np.nan,3,np.nan,5,np.nan,7])
numvalues.isnull().sum()

In [ ]:
# remove null values
numvalues.dropna()

In [ ]:
# replace null values with mean
numvalues.fillna(numvalues.mean())

In [ ]:
#isin
runs[runs.isin([100,46,55])]

In [ ]:
#apply
subs.apply(lambda x:'Bad day'if x > subs.mean() else 'Bad day')

In [ ]:
Movies.apply(lambda x: x.split()[0].upper())

### Plotting Graphs on Series

In [ ]:
subs.plot()

In [ ]:
Movies.value_counts().head(20)

In [ ]:
Movies.value_counts().head(20).plot(kind='bar')

In [ ]:
# Pandas Day 1 — complete list of functions & attributes used
# pd.Series()
# pd.read_csv()
# .squeeze()  # convert single-column read to Series
# pd.Series(..., index=...)
# pd.Series(..., name=...)
# .size
# .dtype
# .name
# .is_unique
# .index
# .values
# .head()
# .tail()
# .sample()
# .value_counts()
# .sort_values()  # includes inplace variant
# .sort_index()
# .count()
# .sum()
# .prod()
# .mean()
# .median()
# .mode()
# .std()
# .var()
# .min()
# .max()
# .describe()
# indexing / slicing (s[a:b])
# .iloc  # positional indexing
# .loc   # label-based indexing
# fancy indexing (s[[i,j,k]])
# assignment to Series elements by label or position
