# What is numpy
numpy is a fundamental package for scienctific computing in python.it is a Python library that provides a multidimansional array object,various derived objects

In [1]:
# Import Numpy library
import numpy as np

## Numpy Arrays Vs Sequence
- Python sequence stores mixed data types; NumPy array usually stores same data type.
- Python sequence is slower; NumPy array is faster for large data.
- Python sequence uses more memory; NumPy array uses less memory.
- Python sequence needs loops for math; NumPy array does math directly.
- Python list * 2 repeats data; NumPy array * 2 multiplies each element.
- Python sequence is good for normal coding; NumPy array is best for data science, ML, and numerical

In [2]:
# c=[1,2,3,4,5]
# for i in range(len(a)):
#     c.append(a[i]*b[i])

In [3]:
# for (i=0; i<rows; i++){
#     c[i]=a[i]*b[i]
# }

# Create Numpy Arrays

In [4]:
# it is a 1D array
a=np.array([1,2,3])
print(type(a))
print(a)


<class 'numpy.ndarray'>
[1 2 3]


In [5]:
# 2D and 3D arrays
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
#3D array
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
#dtype
np.array([1,2,3],dtype=float)
np.array([1,0,1],dtype=bool)

array([ True, False,  True])

In [8]:
#np.range()
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [9]:
np.arange(0,7,2).reshape(2,2)

array([[0, 2],
       [4, 6]])

In [10]:
#np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.random.random((2,3))

array([[0.0400783 , 0.4734868 , 0.28701513],
       [0.16724463, 0.39170965, 0.11383654]])

In [13]:
# np.linspace() -> linear space
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Array Attributes

In [14]:
a1=np.arange(1,10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a4=np.arange(16).reshape(2,2,2,2)

In [15]:
#ndin: check the dimension of the array
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)
print(a4.ndim)

1
2
3
4


In [16]:
#shape: How many rows and columns how many elements in each dimension
print(a2.shape)
print(a3.shape)
print(a4.shape)


(3, 4)
(2, 2, 2)
(2, 2, 2, 2)


In [17]:
# Size: total number of elements in the array
print(a3.size)

8


In [18]:
#itemsize: size of each element in bytes
x=np.array([1,2,3],dtype=np.int32)
print(x.itemsize)
print(x.dtype)

4
int32


# Changing Datatype

In [19]:
#astype: to change the data type of the array
a3.dtype

dtype('int64')

In [20]:
a3.astype(np.int32) # change int64 to int32

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## Array Operations

In [21]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Scalar Operation
- Arithmatic operations

In [22]:
# airthmatic operations
a1*2


array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [23]:
# relational operations
a1>5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

- Vector Operations

In [24]:
# aithmetic operations
a1+a2 

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [25]:
a1>a2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

# Array Functions
- Min / Max / Sum / Product

In [26]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[64., 13., 37.],
       [36., 44., 85.],
       [ 4., 89., 36.]])

In [27]:
# min/ max / sum / product 
a1.astype(np.int32)
print(f"Minimum value: {np.min(a1)}")
print(f"Maximum value: {np.max(a1)}")
print(f"Sum: {np.sum(a1)}")
print(f"Product: {np.prod(a1)}")


Minimum value: 4.0
Maximum value: 89.0
Sum: 408.0
Product: 53119215452160.0


In [28]:
#axis in max/ min / sum / product
np.max(a1, axis=0) # column wise max
a1.min(axis=1) # row wise min

array([13., 36.,  4.])

- mean / Median / Std / Var

In [29]:
print(np.mean(a1,axis=1)) # mean of all elements
print(np.median(a1,axis=1)) # median of all elements in each row
print(np.std(a1,axis=1)) # standard deviation of all elements in each row
print(np.var(a1,axis=1)) # variance of all elements in each row

# only need first row mean, median, std, var
print(np.mean(a1[0])) # mean of first row
# only need first column mean, median, std, var
print(np.mean(a1[:,0])) # mean of first column

[38. 55. 43.]
[37. 44. 36.]
[20.83266666 21.46314671 35.05234181]
[ 434.          460.66666667 1228.66666667]
38.0
34.666666666666664


- trignomatric function

In [30]:
np.sin(a1)

array([[ 0.92002604,  0.42016704, -0.64353813],
       [-0.99177885,  0.01770193, -0.17607562],
       [-0.7568025 ,  0.86006941, -0.99177885]])

- dot product

In [31]:
# dot product
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
np.dot(a1,a2)

array([[19, 22],
       [43, 50]])

- Log and Exponents

In [32]:
# log callulate log of each element in the array
np.log(a1)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [33]:
# exponential calculate exponential of each element in the array
np.exp(a1)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

- Round / Floor / Ceil

In [34]:
#round: round the elements in the array to the nearest integer
np.round(np.random.random((2,2))*100)

array([[33., 73.],
       [ 8., 96.]])

In [35]:
# floor: round the elements in the array to the nearest integer towards negative infinity
np.floor(np.random.random((2,2))*100)

array([[17., 52.],
       [75., 49.]])

In [36]:
# ceil: round the elements in the array to the nearest integer towards positive infinity
np.ceil(np.random.random((2,2))*100)

array([[ 1., 34.],
       [72., 24.]])

## Indexing and Slicing

- indexing

In [37]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [38]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
#INdexing: indiexing is used to access the elements of the array
a1[2] # first element of the array

np.int64(2)

In [40]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
a2[1][0] # python way tho indexing
a2[1,1] # numpy way tho indexing

np.int64(5)

In [42]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [43]:
a3[1,0,1] # numpy way tho indexing
a3[1][0][1] # python way tho indexing

np.int64(5)

- slicing

In [44]:
a1[2:5]

array([2, 3, 4])

In [45]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
print(f"First Row:a2= {a2[0,:]}") # 1st row of the array
print(f"Third Column:a2= {a2[:,2]}") # 3rd column of the array

First Row:a2= [0 1 2 3]
Third Column:a2= [ 2  6 10]


In [47]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [48]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [49]:
a2[::2,1::2] # print 1 3 9 11

array([[ 1,  3],
       [ 9, 11]])

In [50]:
a2[1,::3]

array([4, 7])

In [51]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [52]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [53]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [54]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [55]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [56]:
a3[0,1,:]

array([3, 4, 5])

In [57]:
a3[1,:,1]

array([10, 13, 16])

In [58]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [59]:
a3[::2,::2,::2]

array([[[ 0,  2],
        [ 6,  8]],

       [[18, 20],
        [24, 26]]])

In [60]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iteration Loop

In [61]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [64]:
a1
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [65]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [66]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [67]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [68]:
y= [i for i in np.nditer(a3)]
print(y)

[array(0), array(1), array(2), array(3), array(4), array(5), array(6), array(7), array(8), array(9), array(10), array(11), array(12), array(13), array(14), array(15), array(16), array(17), array(18), array(19), array(20), array(21), array(22), array(23), array(24), array(25), array(26)]


# Reshaping

In [69]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
# transpose: transpose is used to change the shape of the array
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [71]:
# Rshape: reshape is used to change the shape of the array
np.reshape(a2, (1,12)) # 1D to 2D array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [72]:
#ravel: ravel is used to flatten the array
np.ravel(a2)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# Stacking

In [73]:
x=np.arange(12).reshape(3,4)
y=np.arange(12,24).reshape(3,4)

- Horizontal stacking


In [74]:
np.hstack((x,y))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

- Vertical Stack

In [75]:
np.vstack((x,y))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [76]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
np.hsplit(x,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [78]:
np.vsplit(x,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]