## Important Functions()

### np.sort()
- https://numpy.org/doc/stable/reference/generated/numpy.sort.html<br>

In [1]:
# Sort
import numpy as np
a=np.random.randint(1,100,15)
a

array([98, 26, 89, 19, 97, 60, 30, 80, 90, 39, 72, 58, 91, 30, 87],
      dtype=int32)

In [2]:
np.sort(a)

array([ 2,  3, 14, 16, 20, 22, 43, 56, 60, 63, 69, 78, 79, 81, 99],
      dtype=int32)

In [3]:
# Reverse order sorting
np.sort(a)[::-1]

array([99, 81, 79, 78, 69, 63, 60, 56, 43, 22, 20, 16, 14,  3,  2],
      dtype=int32)

In [4]:
b=np.random.randint(1,100,15).reshape(3,5)
b

array([[69, 97, 12, 27, 56],
       [45, 93, 88, 61, 40],
       [36, 17, 68, 35,  6]], dtype=int32)

In [5]:
#2D
np.sort(b)[::-1]

array([[ 6, 17, 35, 36, 68],
       [40, 45, 61, 88, 93],
       [12, 27, 56, 69, 97]], dtype=int32)

### ap.append()
- https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [6]:
np.append(a,200)

array([ 69,  63,  14,  78,  56,  43,  81,  60,  20,   3,  16,  22,  99,
         2,  79, 200])

In [7]:
np.append(b,np.random.randint(1,100,(b.shape[0],1)),axis=1)

array([[69, 97, 12, 27, 56, 85],
       [45, 93, 88, 61, 40, 51],
       [36, 17, 68, 35,  6, 14]], dtype=int32)

In [8]:
np.append(b, np.random.randint(1, 100, (1, b.shape[1])), axis=0)

array([[69, 97, 12, 27, 56],
       [45, 93, 88, 61, 40],
       [36, 17, 68, 35,  6],
       [51, 40, 72, 44, 61]], dtype=int32)

### np.concatenate()
- https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [9]:
# np.concatenate()
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [10]:
np.concatenate((c,d),axis=0) # row wise concatenation

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
np.concatenate((c,d),axis=1) # column wise concatenation

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique()
- https://numpy.org/doc/stable/reference/generated/numpy.unique.html

In [12]:
#np.unique(a)
a=np.array([1,1,1,2,2,2,3,3,3,4,4,4,5,5,5])
np.unique(a)

array([1, 2, 3, 4, 5])

### np.expend_dims()

In [13]:
# np.expand_dims() - to add a new axis
x=np.array(np.random.randint(1,10,10))
x

array([2, 4, 1, 5, 7, 1, 6, 3, 7, 3], dtype=int32)

In [14]:
np.shape(x)

(10,)

In [15]:
np.expand_dims(x,axis=0).shape # to add a new axis at row level


(1, 10)

In [16]:
print(np.expand_dims(x,axis=1))
print(np.expand_dims(x,axis=1).shape)

[[2]
 [4]
 [1]
 [5]
 [7]
 [1]
 [6]
 [3]
 [7]
 [3]]
(10, 1)


### np.where()
- https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [17]:
x

array([2, 4, 1, 5, 7, 1, 6, 3, 7, 3], dtype=int32)

In [18]:
# np.where() - to get the index of the element which satisfies the condition
np.where(x>3)

(array([1, 3, 4, 6, 8]),)

In [19]:
np.where(x>3,"a chota hai",x)

array(['2', 'a chota hai', '1', 'a chota hai', 'a chota hai', '1',
       'a chota hai', '3', 'a chota hai', '3'], dtype='<U11')

In [20]:
np.where(x%2==0,0,x)

array([0, 0, 1, 5, 7, 1, 0, 3, 7, 3], dtype=int32)

### Np.argmax()
- https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [21]:
x

array([2, 4, 1, 5, 7, 1, 6, 3, 7, 3], dtype=int32)

In [22]:
# to get the index of the maximum element in the array
np.argmax(x) 

np.int64(4)

In [23]:
b

array([[69, 97, 12, 27, 56],
       [45, 93, 88, 61, 40],
       [36, 17, 68, 35,  6]], dtype=int32)

In [24]:
# to get the index of the maximum element in each row
np.argmax(b,axis=0) 

array([0, 0, 1, 1, 0])

### np.argmin()
- https://numpy.org/doc/stable/reference/generated/numpy.argmin.html#numpy.argmin

In [25]:
x

array([2, 4, 1, 5, 7, 1, 6, 3, 7, 3], dtype=int32)

In [26]:
# Show minimum value index in the array
np.argmin(x)

np.int64(2)

### np.cumsum()
- https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [27]:
x

array([2, 4, 1, 5, 7, 1, 6, 3, 7, 3], dtype=int32)

In [28]:
#1D array cumulative sum
np.cumsum(x)

array([ 2,  6,  7, 12, 19, 20, 26, 29, 36, 39])

In [29]:
#2D array cumulative sum 
b

array([[69, 97, 12, 27, 56],
       [45, 93, 88, 61, 40],
       [36, 17, 68, 35,  6]], dtype=int32)

In [30]:
np.cumsum(b,axis=1)

array([[ 69, 166, 178, 205, 261],
       [ 45, 138, 226, 287, 327],
       [ 36,  53, 121, 156, 162]])

### np.cumprod()
- https://numpy.org/doc/stable/reference/generated/numpy.cumprod.html

In [31]:
x

array([2, 4, 1, 5, 7, 1, 6, 3, 7, 3], dtype=int32)

In [32]:
np.cumprod(x)

array([     2,      8,      8,     40,    280,    280,   1680,   5040,
        35280, 105840])

### np.percentile()
- https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [33]:
x

array([2, 4, 1, 5, 7, 1, 6, 3, 7, 3], dtype=int32)

In [34]:
np.percentile(x,100)

np.float64(7.0)

In [35]:
np.percentile(x,0)

np.float64(1.0)

In [36]:
np.median(x)

np.float64(3.5)

### np.histogram()
- http://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [37]:
y=np.random.randint(1,100,10)
y

array([77,  9, 68, 55, 83, 50, 32, 34, 25, 35], dtype=int32)

In [38]:
# histogram
np.histogram(y,bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

(array([1, 0, 1, 3, 0, 2, 1, 1, 1, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [39]:
# histogram
np.histogram(y,bins=[0, 50, 100])

(array([5, 5]), array([  0,  50, 100]))

### np.corrcoef()
- https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [40]:
# Correlation
salary=np.array([20000,40000,10000,15000,25000])
Experience=np.array([3,5,1,2,4])
np.corrcoef(salary,Experience)


array([[1.        , 0.96152395],
       [0.96152395, 1.        ]])

### np.isin()
- https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [41]:
items=np.array([10,20,30,40,50,60,70,80,90])
np.isin(items, np.array([10,20,30]))

array([ True,  True,  True, False, False, False, False, False, False])

### np.flip()
- https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [42]:
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [43]:
np.flip(a)

array([5, 5, 5, 4, 4, 4, 3, 3, 3, 2, 2, 2, 1, 1, 1])

In [44]:
b

array([[69, 97, 12, 27, 56],
       [45, 93, 88, 61, 40],
       [36, 17, 68, 35,  6]], dtype=int32)

In [45]:
# row fliping and colomn flipping
np.flip(b)

array([[ 6, 35, 68, 17, 36],
       [40, 61, 88, 93, 45],
       [56, 27, 12, 97, 69]], dtype=int32)

### np.put()
- https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [46]:
x

array([2, 4, 1, 5, 7, 1, 6, 3, 7, 3], dtype=int32)

In [47]:
np.put(x,[0,1],[100,200])
x

array([100, 200,   1,   5,   7,   1,   6,   3,   7,   3], dtype=int32)

### np.delete()
-https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [48]:
x

array([100, 200,   1,   5,   7,   1,   6,   3,   7,   3], dtype=int32)

In [49]:
np.delete(x,[0,1])

array([1, 5, 7, 1, 6, 3, 7, 3], dtype=int32)

### Set Funtions()
- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [50]:
# union in 1d 
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [51]:
# intersection in 1d
np.intersect1d(m,n)

array([3, 4, 5])

In [52]:
# symmetric difference in 1d
np.setdiff1d(m,n)

array([1, 2])

In [53]:
# set xor symmetric difference in 1d
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [54]:
# # use np.in1d()
# np.in1d(1, m)

### np.clip()
- https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [55]:
x

array([100, 200,   1,   5,   7,   1,   6,   3,   7,   3], dtype=int32)

In [56]:
# np.clip() - to limit the values in an array
np.clip(x,a_min=3,a_max=7)

array([7, 7, 3, 5, 7, 3, 6, 3, 7, 3], dtype=int32)

### np.full()
np.full(shape, value)

In [57]:
array3 = np.full(10,3)
array3

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [58]:
array4 = np.full((3,4), 'python')
array4

array([['python', 'python', 'python', 'python'],
       ['python', 'python', 'python', 'python'],
       ['python', 'python', 'python', 'python']], dtype='<U6')

In [59]:
array4 = np.full((3,4), 8.7)
array4

array([[8.7, 8.7, 8.7, 8.7],
       [8.7, 8.7, 8.7, 8.7],
       [8.7, 8.7, 8.7, 8.7]])

### eye()
- if we wan to create identity matrix with row and column
- syntax
np.eye(shape, dtype = int)


In [60]:
array = np.eye(5)
array


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
array = np.eye(5, dtype = int)
array

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [62]:
array = np.eye(5,4, dtype = int)
array

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])