## Important Functions()

### np.sort(a, axis=-1, kind=None, order=None, *, stable=None)
- https://numpy.org/doc/stable/reference/generated/numpy.sort.html<br>
Row = axis=1<br>
Col = axis=2<br>
kind{‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}<br>
orderstr or list of str, optional

In [27]:
# Sort
import numpy as np
a=np.random.randint(1,100,15)
a

array([95,  7, 40, 18, 38, 64, 94, 96, 82, 24, 35, 63, 22, 24,  4],
      dtype=int32)

In [28]:
np.sort(a)

array([ 4,  7, 18, 22, 24, 24, 35, 38, 40, 63, 64, 82, 94, 95, 96],
      dtype=int32)

In [29]:
# Reverse order sorting
np.sort(a)[::-1]

array([96, 95, 94, 82, 64, 63, 40, 38, 35, 24, 24, 22, 18,  7,  4],
      dtype=int32)

In [30]:
b=np.random.randint(1,100,15).reshape(3,5)
b

array([[51, 81, 12, 11,  4],
       [16, 52, 65, 71, 84],
       [20, 65, 68, 35, 40]], dtype=int32)

In [31]:
#2D
np.sort(b)[::-1]

array([[20, 35, 40, 65, 68],
       [16, 52, 65, 71, 84],
       [ 4, 11, 12, 51, 81]], dtype=int32)

### ap.append()
- https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [32]:
np.append(a,200)

array([ 95,   7,  40,  18,  38,  64,  94,  96,  82,  24,  35,  63,  22,
        24,   4, 200])

In [33]:
np.append(b,np.random.randint(1,100,(b.shape[0],1)),axis=1)

array([[51, 81, 12, 11,  4, 22],
       [16, 52, 65, 71, 84, 25],
       [20, 65, 68, 35, 40, 70]], dtype=int32)

In [34]:
np.append(b, np.random.randint(1, 100, (1, b.shape[1])), axis=0)

array([[51, 81, 12, 11,  4],
       [16, 52, 65, 71, 84],
       [20, 65, 68, 35, 40],
       [ 8, 38, 22, 43, 71]], dtype=int32)

### np.concatenate()
- https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [35]:
# np.concatenate()
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [36]:
np.concatenate((c,d),axis=0) # row wise concatenation

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
np.concatenate((c,d),axis=1) # column wise concatenation

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique()
- https://numpy.org/doc/stable/reference/generated/numpy.unique.html

In [38]:
#np.unique(a)
a=np.array([1,1,1,2,2,2,3,3,3,4,4,4,5,5,5])
np.unique(a)

array([1, 2, 3, 4, 5])

### np.expend_dims()

In [39]:
# np.expand_dims() - to add a new axis
x=np.array(np.random.randint(1,10,10))
x

array([5, 1, 2, 1, 6, 5, 2, 6, 6, 6], dtype=int32)

In [40]:
np.shape(x)

(10,)

In [41]:
np.expand_dims(x,axis=0).shape # to add a new axis at row level


(1, 10)

In [42]:
print(np.expand_dims(x,axis=1))
print(np.expand_dims(x,axis=1).shape)

[[5]
 [1]
 [2]
 [1]
 [6]
 [5]
 [2]
 [6]
 [6]
 [6]]
(10, 1)


### np.where()
- https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [43]:
x

array([5, 1, 2, 1, 6, 5, 2, 6, 6, 6], dtype=int32)

In [44]:
# np.where() - to get the index of the element which satisfies the condition
np.where(x>3)

(array([0, 4, 5, 7, 8, 9]),)

In [45]:
np.where(x>3,"a chota hai",x)

array(['a chota hai', '1', '2', '1', 'a chota hai', 'a chota hai', '2',
       'a chota hai', 'a chota hai', 'a chota hai'], dtype='<U11')

In [46]:
np.where(x%2==0,0,x)

array([5, 1, 0, 1, 0, 5, 0, 0, 0, 0], dtype=int32)

### Np.argmax()
- https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [47]:
x

array([5, 1, 2, 1, 6, 5, 2, 6, 6, 6], dtype=int32)

In [48]:
# to get the index of the maximum element in the array
np.argmax(x) 

np.int64(4)

In [49]:
b

array([[51, 81, 12, 11,  4],
       [16, 52, 65, 71, 84],
       [20, 65, 68, 35, 40]], dtype=int32)

In [50]:
# to get the index of the maximum element in each row
np.argmax(b,axis=0) 

array([0, 0, 2, 1, 1])

### np.argmin()
- https://numpy.org/doc/stable/reference/generated/numpy.argmin.html#numpy.argmin

In [51]:
x

array([5, 1, 2, 1, 6, 5, 2, 6, 6, 6], dtype=int32)

In [52]:
# Show minimum value index in the array
np.argmin(x)

np.int64(1)

### np.cumsum()
- https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [53]:
x

array([5, 1, 2, 1, 6, 5, 2, 6, 6, 6], dtype=int32)

In [54]:
#1D array cumulative sum
np.cumsum(x)

array([ 5,  6,  8,  9, 15, 20, 22, 28, 34, 40])

In [55]:
#2D array cumulative sum 
b

array([[51, 81, 12, 11,  4],
       [16, 52, 65, 71, 84],
       [20, 65, 68, 35, 40]], dtype=int32)

In [56]:
np.cumsum(b,axis=1)

array([[ 51, 132, 144, 155, 159],
       [ 16,  68, 133, 204, 288],
       [ 20,  85, 153, 188, 228]])

### np.cumprod()
- https://numpy.org/doc/stable/reference/generated/numpy.cumprod.html

In [57]:
x

array([5, 1, 2, 1, 6, 5, 2, 6, 6, 6], dtype=int32)

In [58]:
np.cumprod(x)

array([     5,      5,     10,     10,     60,    300,    600,   3600,
        21600, 129600])

### np.percentile()
- https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [59]:
x

array([5, 1, 2, 1, 6, 5, 2, 6, 6, 6], dtype=int32)

In [60]:
np.percentile(x,100)

np.float64(6.0)

In [61]:
np.percentile(x,0)

np.float64(1.0)

In [65]:
np.median(x)

np.float64(5.0)

### np.histogram()
- http://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [72]:
y=np.random.randint(1,100,10)
y

array([34,  8,  9, 17, 44, 27, 74, 53,  6, 53], dtype=int32)

In [73]:
# histogram
np.histogram(y,bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

(array([3, 1, 1, 1, 1, 2, 0, 1, 0, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [74]:
# histogram
np.histogram(y,bins=[0, 50, 100])

(array([7, 3]), array([  0,  50, 100]))

### np.corrcoef()
- https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [76]:
# Correlation
salary=np.array([20000,40000,10000,15000,25000])
Experience=np.array([3,5,1,2,4])
np.corrcoef(salary,Experience)


array([[1.        , 0.96152395],
       [0.96152395, 1.        ]])

array([[1.       , 0.2865573],
       [0.2865573, 1.       ]])

### np.isin()
- https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [88]:
items=np.array([10,20,30,40,50,60,70,80,90])
np.isin(items, np.array([10,20,30]))

array([ True,  True,  True, False, False, False, False, False, False])

### np.flip()
- https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [93]:
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [94]:
np.flip(a)

array([5, 5, 5, 4, 4, 4, 3, 3, 3, 2, 2, 2, 1, 1, 1])

In [95]:
b

array([[51, 81, 12, 11,  4],
       [16, 52, 65, 71, 84],
       [20, 65, 68, 35, 40]], dtype=int32)

In [ ]:
# row fliping and colomn flipping
np.flip(b)

array([[40, 35, 68, 65, 20],
       [84, 71, 65, 52, 16],
       [ 4, 11, 12, 81, 51]], dtype=int32)

### np.put()
- https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [98]:
x

array([5, 1, 2, 1, 6, 5, 2, 6, 6, 6], dtype=int32)

In [108]:
np.put(x,[0,1],[100,200])
x

array([100, 200,   2,   1,   6,   5,   2,   6,   6,   6], dtype=int32)

### np.delete()
-https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [109]:
x

array([100, 200,   2,   1,   6,   5,   2,   6,   6,   6], dtype=int32)

In [110]:
np.delete(x,[0,1])

array([2, 1, 6, 5, 2, 6, 6, 6], dtype=int32)

### Set Funtions()
- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [ ]:
# union in 1d 
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# intersection in 1d
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
# symmetric difference in 1d
np.setdiff1d(m,n)

array([1, 2])

In [ ]:
# set xor symmetric difference in 1d
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [122]:
# # use np.in1d()
# np.in1d(1, m)

### np.clip()
- https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [123]:
x

array([100, 200,   2,   1,   6,   5,   2,   6,   6,   6], dtype=int32)

In [125]:
# np.clip() - to limit the values in an array
np.clip(x,a_min=3,a_max=7)

array([7, 7, 3, 3, 6, 5, 3, 6, 6, 6], dtype=int32)